apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: sample-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: sample-app
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust