apiVersion: apps/v1
kind: Deployment
metadata: 
  name: voting-app-deployment
  labels:
    name: voting-app-deployment
    app: example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod
      app: example-deployment
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: example-deployment
    spec:
      containers:
        - name: voting-app-pod
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80