apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app-service
    app: sample-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-pod
    app: sample-app